# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://drewbwarren.github.io
title: Drew Warren
email: drewbwarren@gmail.com
author: Drew Warren
description: > # "Write an awesome description for your new site here. 
    This is a project portfolio site for Drew Warren. It was created using Jekyll based on the Landing Page template. Projects are included from Drew's time as an undergraduate student at Brigham Young Universtiy and a master's student at Northwestern University.
copyright: 'Copyright &copy; 2017 Drew Warren. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: file
    url: https://drewbwarren.github.io/download/2017-10-17-Drew_Warren_Resume.pdf
  - title: github
    url: https://github.com/drewbwarren
  - title: linkedin
    url: https://www.linkedin.com/in/andrew-warren-90808ab0/
